# Generated by Django 5.2.1 on 2025-05-30 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_item_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
